/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATTPCFlow: typeof import('./src/components/ATTPCFlow.vue')['default']
    ExecutionProgressPanel: typeof import('./src/components/ExecutionProgressPanel.vue')['default']
    FloatingButtons: typeof import('./src/components/FloatingButtons.vue')['default']
    FlowCanvas: typeof import('./src/components/FlowCanvas.vue')['default']
    FlowNode: typeof import('./src/components/FlowNode.vue')['default']
    RunSelector: typeof import('./src/components/RunSelector.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    TopAppBar: typeof import('./src/components/TopAppBar.vue')['default']
    WelcomePage: typeof import('./src/components/WelcomePage.vue')['default']
  }
}
