/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ATFlow: typeof import('./src/components/ATFlow.vue')['default']
    ATTPCFlow: typeof import('./src/components/ATTPCFlow.vue')['default']
    ComfyUI: typeof import('./src/components/ComfyUI.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    TopAppBar: typeof import('./src/components/TopAppBar.vue')['default']
  }
}
