[project]
name = "attpc-flow"
version = "0.1.0"
description = "Analysis tool for AT-TPC in workflow."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "kinstaky" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "fastapi>=0.129.0",
    "colorlog>=6.0.0",
    "httpx>=0.28.1",
    "pydantic >=2.12",
    "pytest>=9.0.2",
    "pyzmq >=27.1.0",
    "tqdm >=4.67.3",
    "uvicorn[standard]>=0.40.0",
    "polars>=1.38.1",
    "attpc-flow-cpp",
    "attpc-flow-frontend",
]

[project.optional-dependencies]
merger = ["attpc-merger-wrapper"]

[project.urls]
Homepage = "https://github.com/kinstaky/attpc_flow"

[project.scripts]
atflow = "atflow.launcher:main"


[build-system]
requires = ["uv-build>=0.10.2,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "atflow"
module-root = "python"

[tool.uv.sources]
attpc-flow = { workspace = true }
attpc-flow-cpp = { workspace = true }
attpc-flow-frontend = { workspace = true }
attpc-merger-wrapper = { workspace = true }

[tool.uv.workspace]
members = [
    "attpc_flow_cpp",
    "frontend",
    "packages/attpc_merger_wrapper",
]